#! /bin/bash

cf purge-service-offering dummy -f
cf purge-service-offering dummy-dev -f
cf purge-service-offering sendgrid -f
cf purge-service-offering sendgrid-dev -f
cf purge-service-offering newrelic -f
cf purge-service-offering newrelic-dev -f
cf purge-service-offering urbanairship -f
cf purge-service-offering urbanairship-dev -f
cf purge-service-offering treasuredata -f
cf purge-service-offering treasuredata-dev -f
cf purge-service-offering blazemeter -f
cf purge-service-offering blazemeter-dev -f
cf purge-service-offering searchify -f
cf purge-service-offering searchify-dev -f
cf purge-service-offering cleardb -f
cf purge-service-offering cleardb-dev -f
cf purge-service-offering mongolab -f
cf purge-service-offering mongolab-dev -f
cf purge-service-offering rediscloud -f
cf purge-service-offering rediscloud-dev -f
cf purge-service-offering elephantsql -f
cf purge-service-offering elephantsql-dev -f
cf purge-service-offering cloudamqp -f
cf purge-service-offering cloudamqp-dev -f
cf purge-service-offering memcachedcloud -f
cf purge-service-offering memcachedcloud-dev -f
cf purge-service-offering memcachier -f
cf purge-service-offering memcachier-dev -f
cf purge-service-offering searchly -f
cf purge-service-offering searchly-dev -f
cf purge-service-offering loadimpact -f
cf purge-service-offering loadimpact-dev -f
